### ISSUE TITLE
Missing files

### ISSUE THREAD

**Issue by mannamsam** [javydekoning/amazon-lex-teams-adapter#1]
Missing following files in the repo. Can you please commit them.

from app.lib.lex_teams_adapter import LexTeamsAdapter, LexTeamsAdapterConfig

Thanks
Ram

**Comment by javydekoning** [comment]
There was an error in my .gitignore added the missing file from an old copy on disk. Not sure if it will work, haven't touched this example code in some time. Let me know if you have any issues, might have a copy in a private repo somewhere that I could check.

**Comment by mannamsam** [comment]
Thank you. I will try it out. Appreciate your quick response.

**Comment by iHMFaisal** [comment]
Thank you @javydekoning for this solution. 

Hello @mannamsam, I would like to get this functionality working for my organization. Did you try this out and is it working for you? Any changes in the proposed steps by @javydekoning? Thanks

**Comment by mannamsam** [comment]
@iHMFaisal Yes. We were able to get it working.

**Comment by rashmnai** [comment]
@mannamsam @javydekoning We have followed the steps and created the bot in MS Teams and when we send a message on bot, we see below error on Lambda cloudwatch logs. Is there any additional step that has to be done ?

[ERROR] KeyError: 'name'
Traceback (most recent call last):
  File "/var/task/lambda_function.py", line 39, in lambda_handler
    adapter = LexTeamsAdapter.from_json(config, event['body'])
  File "/opt/python/app/lib/lex_teams_adapter.py", line 48, in from_json
    object["from"]["name"].split(" ")[0],

**Comment by rashmnai** [comment]
@javydekoning Will you be able to guide? We need this implementation for our project.

**Comment by javydekoning** [comment]
You are responding to a closed issue. Can you please open new one and include the full log output? 

Looks like the incoming message / body is missing a name property. I'd like to see the full incoming body
